import cgi
import smtplib
import sys

data = cgi.FieldStorage()
name = data.getvalue('fn')
email = data.getvalue('email')
s = smtplib.SMTP('smtp.gmail.com',587)
s.ehlo()
s.starttls()
s.login(sensitive.myEmail,sensitive.myPass)
for i in data:
    if (i == 'submit1'):
        body = data.getvalue('prob')
        subject= "P.. " + name + " (" + email + ')'
    if (i == 'submit2'):
        body = data.getvalue('topic').upper() + "\n\n" + data.getvalue('derive')
        subject= "D.. " + name + " (" + email + ')'
    if (i == 'submit3'):
        body = data.getvalue('idea')
        subject= "S.. " + name + " (" + email + ')'

msg = f'Subject:{subject}\n\n{body}'
s.sendmail('contact.deriveit@gmail.com','contact.deriveit@gmail.com',msg)
s.quit()
print("Content-type:text/html\r\n\r\n")
print('<!DOCTYPE HTML>')
print('<HTML lang="en" id="html">')
print('<!--head~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->')
print('<HEAD>')
print('<link rel="stylesheet" type="text/css" href="index.css">')
print('<meta name="viewport" content="width=device-width,initial-scale=1.0">')
print('<meta charset="UTF-8">')
print('<link rel="icon" type="image/png" href="pictures/logo.png">')
print('<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>')
print('<TITLE>DeriveIt</TITLE>')
print('</HEAD>')
print('<!--page~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->')
print('<body id="body">')
print('<div id="loading">')
print('<table id="loadcontain">')
print('	<tr>')
print('		<td id="forline" rowspan="2"><img src="pictures/link_logo.png"></td>')
print('		<td id="betweenBorder" rowspan="2"></td>')
print('		<td id="recommended"><b>Thank You For Your Submission</b><br/>Make sure to check you email for our reply</td>')
print('	</tr>')
print('	<tr><td><button id="continue" onclick="afterLoading()" disabled="disabled">loading</button></td></tr>	')
print('</table>')
print('</div>')
print('<div id="sideborder">')
print('<header>')
print('<h1 id="mainheading">Welcome To <span style="color:#0066FF">Derive</span>It<span style="color:#0066FF">!</span></h1>')
print('</header>')
print('')
print('<nav>')
print('<table id="maintable">')
print('	<tr>')
print('		<td id="ttitle">Choose Your Topic:</td>')
print('	</tr>')
print('	<!--When making images in powerpoint, the width should be 646px and height should be 334px-->')
print('	<tr class="tableb">')
print('		<td>')
print('		<div class="first">')
print('			<div class="second"><a href="algebra/algebra.html"><img class="imginfo" alt="algebra" src="pictures/algebra.png"></a></div>')
print('			<div class="second"><a href="geometry/geometry.html"><img class="imginfo" alt="geometry" src="pictures/geometry.png"></a></div>')
print('		</div>')
print('		</td>')
print('	</tr>')
print('	<tr class="tableb">')
print('		<td>')
print('		<div class="first">')
print('			<div class="second"><a href="dismaths/dismaths.html"><img class="imginfo" alt="discrete mathematics" src="pictures/dismaths.png"></a></div>')
print('			<div class="second"><a href="linear_algebra/linear_algebra.html"><img class="imginfo" alt="linear algebra" src="pictures/linear_algebra.png"></a></div>')
print('		</div>')
print('		</td>')
print('	</tr>')
print('	<tr class="tableb">')
print('		<td>')
print('		<div class="first">')
print('			<div class="second"><a href="trigonometry/trigonometry.html"><img class="imginfo" alt="trigonometry" src="pictures/trigonometry.png"></a></div>')
print('			<div class="second"><a href="calculus/calculus.html"><img class="imginfo" alt="calculus" src="pictures/calculus.png"></a></div>')
print('		</div>')
print('		</td>')
print('	</tr>')
print('	<tr class="tableb">')
print('		<td>')
print('		<div class="first">')
print('			<div class="second"><a href="ps/ps.html"><img class="imginfo" alt="probability and statistics" src="pictures/ps.png"></a></div>')
print('			<div class="second"><a href="mechanics/mechanics.html"><img class="imginfo" alt="mechanics" src="pictures/mechanics.png"></a></div>')
print('		</div>')
print('		</td>')
print('	</tr>')
print('	<tr class="tableb">')
print('		<td>')
print('		<div class="first">')
print('			<div class="second"><a href="astronomy/astronomy.html"><img class="imginfo" alt="astronomy" src="pictures/astronomy.png"></a></div>')
print('			<div class="second"><a href="chemistry/chemistry.html"><img class="imginfo" alt="chemistry" src="pictures/chemistry.png"></a></div>')
print('		</div>')
print('		</td>')
print('	</tr>')
print('	<tr class="tableb">')
print('		<td>')
print('		<div class="first">')
print('			<div class="second"><a href="electricity/electricity.html"><img class="imginfo" alt="electricity" src="pictures/em.png"></a></div>')
print('			<div class="second"><a href="biology/biology.html"><img class="imginfo" alt="biology" src="pictures/biology.png"></a></div>')
print('		</div>')
print('		</td>')
print('	</tr>')
print('</table>')
print('</nav>')
print('')
print('<!-- recently added -->')
print('<table id="tableadded">')
print('	<tr class="tback">')
print('		<td class="ttitle2" rowspan="4"><span style="float:left">Recently</span><span style="float:right">Added</span></td>')
print('		<td class="ttext"><a href="astronomy/heliocentric/heliocentric.html">The Heliocentric View</a></td>')
print('	</tr>')
print('	<tr class="tback">')
print('		<td class="ttext"><a href="calculus/e_as_series/e_series.html">Representing e As An Infinite Series</a></td>')
print('	</tr>')
print('	<tr class="tback">')
print('		<td class="ttext"><a href="calculus/limits/define_e.html">Definition of e</a></td>')
print('	</tr>')
print('	<tr class="tback">')
print('		<td class="ttext"><a href="dismaths/isquare/isquare.html">The Formula For The Sum Of An Arithmetic Series</a></td>')
print('	</tr>')
print('</table>')
print('<!-- recently edited -->')
print('<table id="tableedit">')
print('	<tr class="tback">')
print('		<td class="ttitle2" rowspan="4"><span style="float:left">Recently</span><span style="float:right">Edited</span></td>')
print('		<td class="ttext"><a href="astronomy/heliocentric/heliocentric.html">The Heliocentric View</a></td>')
print('	</tr>')
print('	<tr class="tback">')
print('		<td class="ttext"><a href="calculus/e_as_series/e_series.html">Representing e As An Infinite Series</a></td>')
print('	</tr>')
print('	<tr class="tback">')
print('		<td class="ttext"><a href="astronomy/geocentric/geocentric.html">The Geocentric View</a></td>')
print('	</tr>')
print('	<tr class="tback">')
print('		<td class="ttext"><a href="calculus/limits/limit_sin.html">Proof That sinx/x approaches 1 as x approaches 0</a></td>')
print('	</tr>')
print('</table>')
print('')
print('<!--footer~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->')
print('<footer>')
print('<hr>')
print('<table id="footertd">')
print('	<tr>')
print('		<td class="footertd2" style="width:1000px">If you find a problem in this website or a maths-related mistake, <a href="submitpage1.html" target="_blank">click here</a></td>')
print('		<td rowspan="3" style="text-align:center;width:300px"><A HREF="http://www.aprelium.com" target="_blank"><IMG id="pba" SRC="pictures/pwrabyss.gif" ALT="Powered by Abyss Web Server" TITLE="Powered by Abyss Web Server" style="border-style:solid;border-color:#C79000"></A></td>')
print('	</tr>')
print('	<tr><td class="footertd2">If there are any equations for which you want proof for, <a href="submitpage2.html" target="_blank">click here</a></td></tr>')
print('	<tr><td class="footertd2">For any suggestion and ideas, <a href="submitpage3.html" target="_blank">click here</a></td></tr>')
print('	<tr><td colspan="2" style="">DeriveIt &copy; - All rights reserved</td></tr>')
print('</table>')
print('</footer>')
print('</div>')
print('<div id="bline"></div>')
print('<script src="index.js"></script>')
print('</body>')
print('</HTML>')
